name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Maven
        uses: stCarolas/setup-maven@v1
        with:
          maven-version: 3.5.4
      - name: Build with Maven
        env:
          BSKEY: ${{ secrets.BSKEY }}
          BSUSERNAME: ${{ secrets.BSUSERNAME }}
        run: mvn -B package --file pom.xml
#      - name: Slack Notification
#        uses: gymshark/slack-notifier-action@master
#        if: always()
#        with:
#          job: ${{ toJson(job) }}
#          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
#          channel: '#cicd-status'
#          name: 'QA (Jake)'
#      - uses: actions/upload-artifact@v1
#        with:
#          name: testOutput
#          path: build/reports/tests/test/
